### ISSUE TITLE
[Unconfirmed] Sometimes Server Details fails

### ISSUE THREAD

**Issue by LKDevelopment** [LKDevelopment/hetzner-cloud-mobile-app#39]
Sometimes the Server Details Page has no content.

Steps to reproduce:
**Caution**
This error could actually only be fixed via the Hetzner Cloud Console

Steps:

1. Create a Backup from a Server (Srv1)
2. Create a new Server from the Backup (Srv2)
3. Deactivate the Backup on Srv1 (or Delete the Backup)
4. Go on the Servers List
5. ERROR: The Page freezes and the servers are displayed 0....9999-Times
6. Go to the Hetzner Console and delete Srv2
7. Restart the App complete
8. Reselect the Project
9. All is Good

**Comment by LKDevelopment** [comment]
@janxb Can you please check this? Actually i see the issue only on iPhones

**Comment by LKDevelopment** [comment]
Developer Note:
Looks like the result set from the API is "null":
"null is not an object (evaluating 'e.server.image.description')" - 

In the API Doc the field "image" could be an object or null

**Comment by janxb** [comment]
I can confirm this issue. Please note: I tested it with snapshots and not with backups, because they don't cost me money.. ;)

When deleting the snapshot a server was created from, I get lots of different effects like duplicated servers in the server overview, and empty server details pages. See the attached screenshots for details.

I think it makes sense to return null for the "image" field, because when you delete the source image, there is no other data to be displayed there.

![screenshot-2018-03-02](https://user-images.githubusercontent.com/1172106/36885945-44ed63a0-1dea-11e8-8f34-3680fbfc446c.jpg)
![screenshot-2018-03-02 1](https://user-images.githubusercontent.com/1172106/36885946-45040100-1dea-11e8-80f7-9b451a346904.jpg)
